analyzer_rules:
  - unused_import

opt_in_rules:
  - balanced_xctest_lifecycle
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_string
  - explicit_init
  - extension_access_modifier
  - file_name_no_space
  - implicit_getter
  - implicit_return
  - joined_default_parameter
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiple_closures_with_trailing_closure
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prohibited_super_call
  - redundant_nil_coalescing
  - trailing_comma
  - unneeded_parentheses_in_closure_argument
  - weak_delegate

disabled_rules:
  - duplicate_enum_cases
  - file_length
  - for_where
  - force_cast
  - force_unwrapping
  - identifier_name
  - line_length
  - optional_data_string_conversion
  - nesting
  - todo
  - trailing_whitespace
  - type_body_length
  - type_name

custom_rules:
  customrule_rx_subscribe:
    regex: "[^ (]\\.subscribe\\(onNext"
    message: "Insert a newline before '.subscribe(...)' and re-indent block to align with natural '.disposed(by:' indentation"

  customrule_case_let:
    regex: "case +\\.[A-Za-z0-9]*\\([^\n]*?(let )"
    message: "Move 'let' to directly after 'case'"
    capture_group: 1

  customrule_force_vertical_alignment_with_whitespace:
    regex: "[^ ]( {2,20})[:=]"
    message: "Unexpected whitespace - reconsider spacing!"
    capture_group: 1

  customrule_string_contentsof:
    regex: "String\\(contentsOf:"
    message: "This is a synchronous API call - reconsider or use String(contentsOfFile:) for loading local files"

  customrule_init_nscoder:
    regex: "required init[^\n]*: NSCoder\\) \\{(\n +[fp]| \\S+\"| precon)"
    message: "Simplify to 'required init?(coder: NSCoder) { fatalError() }'"
    capture_group: 1

included:
  - NextToGo
  - Core
  - App
  - Resources
  - Features
  - Tests

excluded:
  - .build/
  - Build/
  - Carthage/
  - fastlane/
  - generate.swift
  - Pods/
  - scripts/fastlane/
  - Tools/
  - vendor/
  - "**/Generated/"
  - "**/*.h"
  - "**/*.m"
  - "**/*.xcodeproj"
  - "**/xcuserdata/"
  - "**/project.xcworkspace/"

weak_delegate: error

cyclomatic_complexity:
  warning: 20
  error: 30

function_body_length:
  warning: 50

large_tuple:
  warning: 5

trailing_comma:
  mandatory_comma: true

multiline_arguments:
  first_argument_location: next_line
